### ISSUE TITLE
/usr/sbin/chronyd: no such file or directory

### ISSUE THREAD

**Issue by atasoglou** [container-images/chronyd#2]
I am getting this error when trying to run it:

`docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"/usr/sbin/chronyd\": stat /usr/sbin/chronyd: no such file or directory".
`
Using either of the commands suggested.

**Comment by TomasTomecek** [comment]
Hi @atasoglou, thanks for opening this issue!

I just verified that this is indeed true. The problem is that there is no chrony module so nothing gets installed. Fix incoming!
